---

- include: repository.yml
  when: rabbitmq_use_upstream_repository
  tags: [repository,rabbitmq]

- include: packages.yml
  tags: [packages,rabbitmq]

- include: config-cluster.yml
  tags: [configuration,rabbitmq]
  when: rabbitmq_create_cluster

- include: config.yml
  tags: [configuration,rabbitmq]

- include: service.yml

- include: cluster.yml
  tags: [rabbitmq]
  when: 'rabbitmq_create_cluster and (ansible_hostname != rabbitmq_cluster_master)'

- include: rabbitmq.yml
  tags: [configuration,rabbitmq]
  when: 'not rabbitmq_create_cluster or (ansible_hostname == rabbitmq_cluster_master)'

- meta: flush_handlers
