---
# Install required packages
- block:
  ## WORKAROUND: python-requests that comes with ubuntu 12.04 is too
  ## old to run ansible rabbitmq setup
  - name: upgrade pip
    pip:
      name: pip
      state: latest
  - name: install python requests
    pip:
      name: requests
  when:
    (
    ansible_distribution == 'Ubuntu'
    and
    ansible_distribution_major_version == '12'
    )

- name: install rabbitmq-server packages via apt
  apt:
    pkg: rabbitmq-server
      {%- if rabbitmq_version != '' -%}
      ={{ rabbitmq_version }}-1
      {%- endif %}
    state: present
    force: yes
  register: rabbitmq_version_in_repo
  ignore_errors: yes

- name: download rabbitmq-server deb from rabbitmq.com
  get_url:
    url: https://www.rabbitmq.com/releases/rabbitmq-server/v{{ rabbitmq_version }}/rabbitmq-server_{{ rabbitmq_version }}-1_all.deb
    dest: /var/cache/apt/archives/rabbitmq-server_{{ rabbitmq_version }}-1_all.deb
  when: rabbitmq_version_in_repo|failed

- name: install rabbitmq-server deb from rabbitmq.com
  apt:
    deb: /var/cache/apt/archives/rabbitmq-server_{{ rabbitmq_version }}-1_all.deb
    state: present
    force: yes
  when: rabbitmq_version_in_repo|failed
