---
# RabbitMQ user and vhost management

- name: Ensure users are removed
  rabbitmq_user: user="{{ item }}" state=absent
  with_items: "{{ rabbitmq_users_removed }}"
  tags: [configuration,rabbitmq]

- name: Ensure vhosts are present
  rabbitmq_vhost: name="{{ item }}"
  with_items: "{{ rabbitmq_vhosts }}"
  tags: [configuration,rabbitmq]

- name: Ensure users are present
  rabbitmq_user:
    user: "{{ item.user }}"
    password: "{{ item.password }}"
    configure_priv: "{{ item.configure_priv|default('.*') }}"
    read_priv: "{{ item.read_priv|default('.*') }}"
    write_priv: "{{ item.write_priv|default('.*') }}"
    vhost: "{{ item.vhost|default('/') }}"
    tags: "{{ item.tags|default('') }}"
  no_log: true  # mask passwords
  with_items: "{{ rabbitmq_users }}"
  tags: [configuration,rabbitmq]

- name: Symlink RabbitMQ bin to sbin
  file: state=link src=/usr/lib/rabbitmq/bin dest=/usr/lib/rabbitmq/sbin
  tags: [configuration,rabbitmq]
  register: symlink_changes

- name: Enable plugins are installed
  rabbitmq_plugin: names="{{ item }}" state=enabled prefix=/usr/lib/rabbitmq new_only=yes
  with_items: "{{ rabbitmq_plugins }}"
  notify: restart rabbitmq-server
  tags: [configuration,rabbitmq]

## rabbitmq may need a restart to enable management plugin
- meta: flush_handlers
- wait_for:
    port: 15672

- name: setup rabbitmq exchange
  rabbitmq_exchange:
    name: "{{ item.exchange_name }}"
    exchange_type: "{{ item.exchange_type|default('direct') }}"
    durable: "{{ item.durable|default('yes') }}"
    vhost: "/{{ item.vhost_name }}"
    login_user: "{{ item.user }}"
    login_password: "{{ item.password }}"
  no_log: true  # mask passwords
  with_items: "{{ rabbitmq_exchanges }}"
  tags: [configuration,rabbitmq]

- name: setup rabbitmq queue
  rabbitmq_queue:
    name: "{{ item.queue_name}}"
    login_user: "{{ item.user}}"
    login_password: "{{item.password}}"
    vhost: "/{{ item.vhost_name}}"
  no_log: true  # mask passwords
  with_items: "{{ rabbitmq_queue }}"
  tags: [configuration,rabbitmq]

- name: setup rabbitmq binding
  rabbitmq_binding:
    vhost: "/{{ item.vhost_name }}"
    source: "{{ item.binding_source }}"
    destination: "{{ item.binding_destination }}"
    destination_type: "{{ item.binding_type }}"
    routing_key: "{{ item.routing_key }}"
    login_user: "{{ item.user }}"
    login_password: "{{ item.password }}"
  no_log: true  # mask passwords
  with_items: "{{ rabbitmq_bindings }}"
  tags: [configuration,rabbitmq]
